steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'REGION-docker.pkg.dev/PROJECT_ID/my-app-repo/my-app-prod:$SHORT_SHA', '.']
    dir: 'app/'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'REGION-docker.pkg.dev/PROJECT_ID/my-app-repo/my-app-prod:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'my-app-prod',
        '--image=REGION-docker.pkg.dev/PROJECT_ID/my-app-repo/my-app-prod:$SHORT_SHA',
        '--region=REGION',
        '--platform=managed',
        '--set-env-vars=ENV=prod',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
