steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-app-dev:$SHORT_SHA", "."]
    dir: "app"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-app-dev:$SHORT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run", "deploy", "my-app-dev",
        "--image=us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-app-dev:$SHORT_SHA",
        "--platform=managed",
        "--region=us-central1",
        "--allow-unauthenticated",
        "--set-env-vars", "ENV=dev"
      ]
